server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:2022/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      connection-test-query: select 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myApp
  swagger-ui:
    path: /swagger-ui.html
  data:
    redis:
      host: localhost
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      port: 6379
